[tool.bandit]
skips = ["B320"]

[tool.coverage.paths]
source = ["src", "*/site-packages"]
tests = ["tests", "*/tests"]

[tool.coverage.run]
branch = true
source = ["dlsite_utils", "tests"]
omit = ["*/site-packages/dlsite_utils/dlst.py"]

[tool.coverage.report]
show_missing = true
fail_under = 100
exclude_lines = ["pragma: no cover", "if TYPE_CHECKING:", "@overload"]

[tool.isort]
profile = "black"
multi_line_output = 3
lines_after_imports = 2

[tool.mypy]
strict = true
warn_unreachable = true
pretty = true
show_column_numbers = true
show_error_codes = true
show_error_context = true

[[tool.mypy.overrides]]
module = ["tqdm"]
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = ["mutagen.*"]
implicit_reexport = true

[tool.pytest.ini_options]
asyncio_mode = "auto"


[tool.pdm]
[tool.pdm.dev-dependencies]
coverage = [
    "coverage[toml]>=7.4.0"
]
docs = [
    "furo>=2023.9.10",
    "myst-parser>=2.0.0",
    "sphinx>=7.2.6",
    "sphinx-click>=5.1.0",
]
lint = [
    "pre-commit>=3.6.0"
]
mypy = [
    "mypy>=1.8.0"
]
tests = [
    "pygments>=2.17.2",
    "pytest>=7.4.3",
    "pytest-asyncio<1.0.0,>=0.21.0",
    "pytest-mock<4.0.0,>=3.8.2",
]
safety = [
    "safety>=2.3.5"
]
typeguard = [
    "typeguard>=4.1.5",
]
xdoctest = [
    "xdoctest[colors]>=1.1.2",
]

[tool.pdm.build]
includes = []

[tool.ruff]
target-version = "py311"

[project]
authors = [
    {name = "byeonhyeok", email = "bhrevol@gmail.com"},
]
license = {text = "MIT"}
requires-python = ">=3.11,<4.0"
dependencies = [
    "click>=8.0.1",
    "dlsite-async>=0.5.1",
    "aiohttp<4.0.0,>=3.8.1",
    "pathvalidate<3.3.0,>=3.2.3",
    "cryptography>=44.0.2",
    "ruamel-yaml<1.0.0,>=0.18.0",
    "tqdm<5.0.0,>=4.64.1",
    "platformdirs<4.4.0,>=4.3.6",
    "Pillow>=10.1.0",
]
name = "dlsite-utils"
version = "0.0.0"
description = "DLsite Utilities"
readme = "README.md"
classifiers = [
    "Development Status :: 4 - Beta",
]

[project.urls]
Changelog = "https://github.com/bhrevol/dlsite-utils/releases"
homepage = "https://github.com/bhrevol/dlsite-utils"
repository = "https://github.com/bhrevol/dlsite-utils"
documentation = "https://dlsite-utils.readthedocs.io"

[project.optional-dependencies]
mutagen = [
    "mutagen<2.0.0,>=1.45.1",
]

[project.scripts]
dlsite = "dlsite_utils.__main__:cli"

[dependency-groups]
dev = [
    "nox>=2023.4.22",
    "pyupgrade>=3.19.1",
]
